version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/personal-website
hooks:
  BeforeInstall:
    - location: deployment-scripts/BeforeInstall.sh
      timeout: 180
  AfterInstall:
    - location: deployment-scripts/AfterInstall.sh
      timeout: 180
  ApplicationStart:
    - location: deployment-scripts/ApplicationStart.sh
      timeout: 180
